apiVersion: v1
kind: Service
metadata:
  name: couchbase
  labels:
    app: concepts
    name: couchbase
    role: service
spec:
  ports:
  - port: 8091
    targetPort: 8091
    name: couchbase
  # *.couchbase.default.svc.cluster.local
  clusterIP: None
  selector:
    app: concepts
    name: couchbase
    role: database
