apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: couchbase-node
spec:
  replicas: 1
  serviceName: "couchbase"
  selector:
    matchLabels:
      app: concepts
      name: couchbase
      role: database
  template:
    metadata:
      labels:
        app: concepts
        name: couchbase
        role: database
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: couchbase-node
          image: gcr.io/YOUR_PROJECT/couchbase
          env:
            - name: CB_REST_USERNAME
              value: Administrator
            - name: CB_REST_PASSWORD
              value: change_me
          ports:
            - containerPort: 8091
          volumeMounts:
          - mountPath: /opt/couchbase/var
            name: couch-data
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/joined_cluster
            initialDelaySeconds: 50
            timeoutSeconds: 1
      imagePullSecrets:
        - name: myregistrykey
  volumeClaimTemplates:
  - metadata:
      name: couch-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 6Gi
